package com.example.abc

val abcImage = listOf<Item>(
    Item("Акула", R.drawable.l1),
    Item("Баран", R.drawable.l2),
    Item("Ворона", R.drawable.l3),
    Item("Гусь", R.drawable.l4),
    Item("Дельфин", R.drawable.l5),
    Item("Енот", R.drawable.l6),
    Item("Ёж", R.drawable.l7),
    Item("Жираф", R.drawable.l8),
    Item("Заяц", R.drawable.l9),
    Item("Индюк", R.drawable.l10),
    Item("Попугай", R.drawable.l11),
    Item("Кот", R.drawable.l12),
    Item("Лиса", R.drawable.l13),
    Item("Медведь", R.drawable.l14),
    Item("Носорог", R.drawable.l15),
    Item("Осёл", R.drawable.l16),
    Item("Петух", R.drawable.l17),
    Item("Рыба", R.drawable.l18),
    Item("Свинья", R.drawable.l19),
    Item("Тигр", R.drawable.l20),
    Item("Утка", R.drawable.l21),
    Item("Фламинго", R.drawable.l22),
    Item("Хамелеон", R.drawable.l23),
    Item("Цыплёнок", R.drawable.l24),
    Item("Черепаха", R.drawable.l25),
    Item("Шимпанзе", R.drawable.l26),
    Item("Щенок", R.drawable.l27),
    Item("Объявление", R.drawable.l28),
    Item("Мышь", R.drawable.l29),
    Item("Олень", R.drawable.l30),
    Item("Эму", R.drawable.l31),
    Item("Юрок", R.drawable.l32),
    Item("Як", R.drawable.l33)
)